DSEG SEGMENT
STRING DB 'HELLO WORLD!$'
DSEG ENDS
CSEG SEGMENT
     ASSUME   CS:CSEG,DS:DSEG
START: MOV AX,DSEG
       MOV DS,AX
       MOV DX,OFFSET STRING
       MOV AH,9
       INT 21H
       MOV AX,4C00H
       INT 21H
CSEG   ENDS
       END START